export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
export const AUTHORIZATION_PROVIDER = Symbol('AUTHORIZATION_PROVIDER');
export const ROLE_ASSIGNMENT_PROVIDER = Symbol('ROLE_ASSIGNMENT_PROVIDER');
export const ACL_PROVIDER = Symbol('ACL_PROVIDER');
