export const ORG_MEMBER_MANAGE_POLICY = Symbol('ORG_MEMBER_MANAGE_POLICY');
export const EVENT_CREATE_POLICY = Symbol('EVENT_CREATE_POLICY');
export const EVENT_MANAGE_POLICY = Symbol('EVENT_MANAGE_POLICY');
export const RESERVATION_READ_POLICY = Symbol('RESERVATION_READ_POLICY');
export const TICKET_READ_POLICY = Symbol('TICKET_READ_POLICY');
